# Generated by Django 4.1.6 on 2023-02-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseteachers",
            name="day_birth",
            field=models.CharField(max_length=128, verbose_name="Birth date"),
        ),
    ]
